name: My Personal Backend Linter

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches:
      - main

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Linters
        working-directory: ./backend
        run: npm install --save-dev eslint eslint-config-airbnb-base eslint-config-prettier eslint-plugin-import eslint-plugin-prettier prettier
      
      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: ./backend