name: My Personal Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
        
      - name: Install Dependencies
        run: npm install
      
      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true